app/routes/generic.py
from flask import Blueprint, render_template, session, redirect, url_for

generic_bp = Blueprint('generic', __name__, template_folder='../templates/generic')

@generic_bp.route('/')
def home():
    if 'user_id' not in session:
        return redirect(url_for('auth.login'))
    return render_template('base1.html', usuario=session,usuario_nome=session.get('user_nome'))

@generic_bp.route('/profile')
def profile():
    if 'user_id' not in session:
        return redirect(url_for('auth.login'))
    return render_template('profile.html', usuario_nome=session.get('user_nome'),usuario_tipo=session.get('tipo_usuario'))

@generic_bp.route('/settings')
def settings():
    if 'user_id' not in session:
        return redirect(url_for('auth.login'))
    return render_template('settings.html', usuario=session)

app/routes/home.py
from flask import Blueprint, render_template, request, sessions,session
from ..models.database import query_db
import re
from app.utils import login_required

home_bp = Blueprint('home', __name__)

@home_bp.route('/')
@login_required
def index():
    nome= session.get('id')
    print(nome)
    return render_template('index.html')

app/routes/vendas.py
from flask import Blueprint, render_template, request, session,redirect,url_for
from ..models.database import query_db, salvar_venda
import re
from app.utils import login_required, acesso, hierarquia
from datetime import datetime
import sqlite3
from flask import current_app


def listar_vendedor():
    conn = sqlite3.connect(current_app.config['DATABASE'])
    cur = conn.cursor()
    cur.execute("SELECT * FROM usuarios WHERE classe_usuario = 'vendedor'")
    vendedores = cur.fetchall()
    cur.close()
    conn.close()
    return vendedores

vendas_bp = Blueprint('vendas', __name__)


def formatar_cpf(cpf):
    cpf= re.sub(r'\D','',cpf)
    if len(cpf) != 11:
        return None
    return f"{cpf[:3]}.{cpf[3:6]}.{cpf[6:9]}-{cpf[9:]}"


@vendas_bp.route('/')
def home():

    return render_template('vendas/home.html')


@vendas_bp.route('/cpf',methods=['GET','POST'])
@login_required

def cpf():
    if request.method == "POST":
        cpf_input = request.form["cpf"]
        tipo=request.form["tipo"]
        # Consulta ao banco por CPF
        cpf= formatar_cpf(cpf_input)
        if not cpf:
            return render_template("vendas/verify.hTml", error="CPF invalido.")
        
        if tipo == "beneficiario":
            coluna = "sCpfUSR"
            tabela = "beneficiarios"
        elif tipo == "responsavel":
            coluna = "sCpfCgcResp"
            tabela = "beneficiarios"
        else:
            return render_template("vendas/verify.html", error="Tipo de busca inválido.")

        
        
        query = f"SELECT * FROM {tabela} WHERE {coluna} = ?"
        result = query_db(query, [cpf], one=False)

        

        return render_template('vendas/lista_cpf.html', result=result)

    return render_template("vendas/verify.html")



@vendas_bp.route('/lista_cpf')
def lista_retorno():    
   
    result = request.args.get('result')
    result('vendas/lista_cpf.html', result=result)


@vendas_bp.route('/nova_venda')
@acesso('vendas','cadastro')
@hierarquia('supervisor','agente','vendedor')
def nova_venda():
    vendedor = listar_vendedor()
    print("Vendedores:", vendedor)  # Para verificar a lista de vendedores

    return render_template('vendas/vendas_form.html', vendedor=vendedor)

@vendas_bp.route('/saldobenef')
@acesso('vendas','cadastro')
@hierarquia('supervisor','agente','vendedor')
def saldos():

    campo_result = request.args.get('campo_result')  # Recebe o parâmetro da URL
    print("campo_result:", campo_result)  # Para verificar o valor completo de campo_result

    if campo_result:
        # Realiza a consulta usando 'campo_result' como parâmetro (por exemplo, 'numero_contrato' ou 'nome_responsavel')
        try:
            query = "SELECT * FROM saldo_benef WHERE contrato = ?"
            result_saldo = query_db(query, [campo_result], one=True)  # Use sua função de consulta ao banco

            if result_saldo:
                return render_template('vendas/vendassaldo.html', result=result_saldo)
        
        except Exception as e:
            return f"Erro: {e}"
    
        return render_template('vendas/vendassaldo.html', error="Nenhum dado encontrado para o contrato.")
    
    return render_template('vendas/vendassaldo.html', error="Parâmetro inválido.")


@vendas_bp.route('venda_form', methods=['GET','POST'])
@login_required
@acesso('vendas','cadastro')
@hierarquia('supervisor','agente','vendedor')


def venda_form():  
    nome_usuario = session.get('user_nome')
    print(nome_usuario)
    
    try:
        print(nome_usuario)
        # Dados da venda
        venda = {
            "numero_proposta": request.form.get('numero_proposta'),
            "data_venda": request.form.get('data_venda'),
            "tipo_contrato": request.form.get('tipo_contrato'),
            "tipo_produto": request.form.get('tipo_produto'),
            "corretor_resp": request.form.get('corretor_resp'),
            "status": "Enviado ao cadastro",
            "digitador": nome_usuario,
            "valor_venda": float(request.form.get('valor_venda', '0').replace(',', '.')),
            "dt_cadastro": datetime.now().strftime("%d-%m-%Y"),
        }

        # Calcular valores adicionais
        venda["taxa_inscricao"] = 15.00 if venda["tipo_contrato"] == "individual" else 30.00
        venda["iss"] = 0.05 if venda["tipo_contrato"] == "empresarial" else 0
        valor_base = venda["valor_venda"] - venda["taxa_inscricao"]
        if venda['iss']>0:
            valor_iss= valor_base * venda['iss']
            valor_base -= valor_iss           
        else:
            valor_iss= 0
            venda["valor_tabela"] = round(valor_base,2)
            

        venda['valor_tabela'] = valor_base
        venda['iss'] = valor_iss
        print(f"Valor base após ISS: {valor_base}")


        # Dados do responsável
        responsavel = {
            "nome": request.form.get('nome_responsavel'),
            "cpf": request.form.get('cpf_responsavel'),
            "data_nascimento": request.form.get('dt_nascimento_responsavel'),
            "endereco": request.form.get('endereco_responsavel'),
            "celular": request.form.get('celular_responsavel'),
            "email": request.form.get('email_responsavel'),
            "estado_civil": request.form.get('estado_cv_responsavel')
        }
        
        

        # Dados do titular
        titular = {
            "nome": request.form.get('nome_beneficiario'),
            "cpf": request.form.get('cpf_beneficiario'),
            "data_nascimento": request.form.get('dt_nascimento_beneficiario'),
            "idade": request.form.get('idade_beneficiario'),
            "endereco": request.form.get('endereco_beneficiario'),
            "celular": request.form.get('celular_titular'),
            "email": request.form.get('email_titular'),
            "estado_civil": request.form.get('estado_cv_beneficiario'),
            "nome_mae": request.form.get('nome_mae_beneficiario'),
            "nome_pai": request.form.get('nome_pai_beneficiario'),
            "sexo": request.form.get('sexo_beneficiario'),
            "quantidade_titular" : 1
        }
        

        # Dados dos dependentes
        quantidade_dependentes = int(request.form.get('quantidade_dependentes', 0))
        dependentes = []
        nomes_dependentes = request.form.getlist('nome_dependente[]')
        cpfs_dependentes = request.form.getlist('cpf_dependente[]')
        datas_nascimento_dependentes = request.form.getlist('dt_nascimento_dependente[]')
        graus_parentesco_dependentes = request.form.getlist('grau_parentesco_dependente[]')
        mae_dependente = request.form.getlist('mae_dependente[]')

        print("Nomes dependentes:", nomes_dependentes)
        print("CPFs dependentes:", cpfs_dependentes)
        print("Datas nascimento dependentes:", datas_nascimento_dependentes)
        print("Graus parentesco dependentes:", graus_parentesco_dependentes)
        print("Mães dependente:", mae_dependente)

        # Usa o menor tamanho entre as listas para evitar erro de index
        num_dependentes = min(
            len(nomes_dependentes),
            len(cpfs_dependentes),
            len(datas_nascimento_dependentes),
            len(graus_parentesco_dependentes),
            len(mae_dependente)
        )

        for i in range(num_dependentes):
            dependente = {
                "nome": nomes_dependentes[i],
                "cpf": cpfs_dependentes[i],
                "data_nascimento": datas_nascimento_dependentes[i],
                "grau_parentesco": graus_parentesco_dependentes[i],
                "mae_dependente": mae_dependente[i]
            }
            print(f"Dependente {i}: {dependente}")
            dependente["cpf_titular"] = titular["cpf"]
            dependente["data_nascimento"] = datetime.strptime(dependente["data_nascimento"], "%Y-%m-%d").strftime("%d/%m/%Y")
            dependentes.append(dependente)
            quantidade_dependentes += 1
        print(f"Quantidade de dependentes: {quantidade_dependentes}")

        venda["vida"] = titular["quantidade_titular"] + quantidade_dependentes
        venda['nome_responsavel'] = responsavel['nome']
        print(venda['nome_responsavel'])
        print(venda["vida"])

        # Salvar os dados no banco
        salvar_venda(venda, responsavel, titular, dependentes)


        return render_template('vendas/concluido.html', venda=venda, responsavel=responsavel, titular=titular, dependentes=dependentes)
    except KeyError as e:
        return f"Erro: chave não encontrada {e}"

    except Exception as e:
        return f"Erro ao processar os dados: {e}"

app/templates/vendas/concluido.html
{% extends 'base1.html' %}

{% block title %}Bem-vindo{% endblock %}

{% block content %}
<br><br><br>
<body class="body">
    <h1>Venda registrada</h1>
    <h3>Venda registrada no banco de dados.</h3>

    <a href=" {{ url_for('finan.pix', desc= 'adesao') }} "><strong>Lançar pagamento</strong></a>

</body>


{% endblock %}

app/templates/vendas/home.html
{% extends 'base1.html' %}

{% block title %}Vendas{% endblock %}

{% block content %}
<div class="container-cards">
    <a class="btn" href="{{ url_for('vendas.cpf') }}">consultar cpf</a> <br>
    <a class="btn" href="https://servicos.receita.fazenda.gov.br/servicos/cpf/consultasituacao/consultapublica.asp" target="_blank">validar cpf na receita</a> <br>
    <a class="btn" href="https://solucoes.receita.fazenda.gov.br/servicos/cnpjreva/cnpjreva_solicitacao.asp" target="_blank">validar cnpj na receita</a>
    <a class="btn" href="{{ url_for('vendas.nova_venda') }}" target="_blank">nova proposta</a>


</div>
<div class="welcome">
        
    <a href="{{ url_for('generic.home') }}" class="btn">Voltar</a>


{% endblock %}

app/templates/vendas/lista_cpf.html
{% extends 'base1.html' %}

{% block title %}resultado de busca{% endblock %}

{% block content %}

<link rel="stylesheet" href="{{ url_for('static', filename='css/tabpix.css') }}">

<div class="container-tab-pix">
    <!-- Botão de fechar -->
    <div class="filter-tab-pix2">
        <a class="close-btn" href="{{ url_for('generic.home') }}" class="close-btn">✖</a>
    </div>
    
     
    
    

    <!-- Título da tabela -->
    <h1 class="table-title-tab-pix">Retorno de pesquisa</h1>
    {% if result %}

    <!-- Tabela de pagamentos -->
    <div class="table-container-tab-pix">
        <table class="table-tab-pix">
            <thead>
                <tr>
                    <th>Contrato</th>
                    <th>Responsável</th>
                    <th>Nome do Beneficiario</th>
                    <th>CPF do Beneficiario</th>
                    <th>Data de cancelamento</th>
                    <th>Motivo de cancelamento</th>
                                        
                </tr>
            </thead>
            <tbody>
                {% for row in result  %}
                <tr>
                    <td>{{ row[4] }}</td>
                    <td>{{ row[2] }}</td>
                    <td>{{row['sNomeUSR']}}</td>
                    <td>{{ row['ScpfUSR'] }}</td>
                    <td>{{ 'ativo' if row[27] == None else row[27] }}</td>
                    <td><a href="{{ url_for('vendas.saldos', contrato=row[4]) }}">{{ 'ativo' if row[25] == None else row[25] }}</a></td>
                    
                    
                </tr>
                {% endfor %}
    {% endif %}
            </tbody>
        </table>
    </div>
</div>


{% endblock %}

app/templates/vendas/result.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Resultado da Pesquisa</title>
    <link rel="stylesheet" href="{{ url_for('static', filename='css/estilos.css') }}">
</head>
<body class="body">
    <div class="divisoria4">
        <h1>Resultado da Consulta</h1>
        {% if result %}
            <div class="result">
                <p><strong>Nome:</strong> {{ result[19] }}</p> <!-- Exemplo de nome, adapte conforme os dados do seu banco -->
                <p><strong>CPF:</strong> {{ cpf }}</p>                
                <p><strong>Data de Nascimento:</strong> {{ result[22] }}</p>
                <p><strong>Plano:</strong> {{ result[28] }}</p> <!-- Exemplo de plano -->
                <p><strong>Motivo de Cancelamento: </strong">{{'ativo' if result[25] == None else result [25]}}</p>
                <p><strong>Data de cancelamento: </strong>{{'ativo' if result[27] == None else result [27]}}</p>
                        <br>
                <p>Para mais informações sobre débito clique <a href="{{ url_for('vendas.saldos',campo_result=result[4]) }}">aqui.</a></p>
            </div>
        {% else %}
            <div class="error">CPF não encontrado no banco de dados.</div>
        {% endif %}
        <a href="{{ url_for('vendas.cpf') }}" class="btn">Voltar</a>
    </div>
</body>
</html>

app/templates/vendas/vendassaldo.html
{% extends 'base1.html' %}

{% block title %}Vendas{% endblock %}

{% block content %}
<br><br
<body class="body">
    <div class="divisoria4">
        <h1>Resultado da Consulta</h1>
        
        {% if result %}
            <div class="result">
                <p><strong>Nome Responsável:</strong> {{ result[1] }}</p> <!-- Nome do responsável -->
                <p><strong>Numero do Contrato:</strong> {{ result[0] }}</p> <!-- Número do contrato -->
                <p><strong>Parcelas em aberto:</strong> {{ result[2] }}</p> <!-- Valor da parcela com 2 casas decimais -->
                <p><strong>Valor Total:</strong> {{ result[4] }}</p> <!-- Valor total com 2 casas decimais -->
            </div>
        {% else %}
            <p class="prince">Registro Financeiro não encontrado.</p>
            <p>Não foi possível encontrar os dados para o contrato especificado, talvez a informação seja muito antiga.</p>
        {% endif %}

        <a href="{{ url_for('vendas.cpf') }}" class="btn">Voltar</a>
        
        
    </div>
</body>

{% endblock %}

app/templates/vendas/verify.html
{% extends 'base1.html' %}

{% block title %}Vendas{% endblock %}

{% block content %}
 
<div class="container">
    <div class="divisoria2">
        <div class="close-btn-container">
            <a class="close-btn" href="{{ url_for('generic.home') }}">X</a>
        </div>
        <h1>Consulta de CPF</h1>
        <form method="POST" class="cpf-form">
            <label for="cpf">Digite o CPF:</label>
            <input type="text" id="cpf" name="cpf" required placeholder="00000000000">
            <label for="tipo">buscando por:</label>
            <select class="selceionador" id="tipo" name="tipo" required>
                <option value="beneficiario">Beneficiarios</option>
                <option value="responsavel">Responsável</option>
            </select>

            <button class="btn" type="submit">Buscar</button>
        </form>

        {% if error %}
            <div class="error">{{ error }}</div>
        {% endif %}
</div>
    </div>
    
{% endblock %}