app/routes/cadastro.py
from flask import Flask, Blueprint, request, render_template, redirect, send_file, url_for,session, current_app, flash, send_from_directory
import os
from datetime import datetime
from werkzeug.utils import secure_filename
from PyPDF2 import PdfMerger
#from pdf2image import convert_from_path
from app.utils import acesso, hierarquia
from ..models.database import query_db, update_db
import sqlite3
import re
import glob

cad_bp = Blueprint('cad', __name__)



@cad_bp.route('/')
def home():
    return render_template('cadastro/home.html')

@cad_bp.route('/doc')
@acesso('cadastro')
def doc_home():
    return render_template('cadastro/doc_home.html')

@cad_bp.route('cnt-acompanhamento')
@acesso('vendas', 'cadastro', 'administrativo','financeiro')
@hierarquia('supervisor','agente','vendedor')

def acompanhar_cnt():
    
    
    conn= sqlite3.connect(current_app.config['DATABASE'])
    cur= conn.cursor()
    resp = request.args.get('resp')
    tipo_usuario = session.get('tipo_usuario')
    lista= request.args.get('lista')
    filtro = request.args.get('filtro')
    print(filtro)
    venda_inicial = request.args.get('venda_inicial')
    venda_final = request.args.get('venda_final')
    print(f"venda_inicial: {venda_inicial}, venda_final: {venda_final}")
    


    print(resp)
    if resp:
        cur.execute("SELECT * FROM venda WHERE corretor_resp = ?", (resp,))
        result = cur.fetchall()
        print(f"result: {result}")
        return render_template('cadastro/acompanhar_cnt.html', result=result, resp=resp)
        
    
    elif lista == 'todos':
            print(f'exibiindo para: {lista}')
            if filtro =='sim':
                return render_template('cadastro/definir.html')
            
    elif venda_final and venda_inicial:      
        
        print(f"Venda inicial: {venda_inicial}, Venda final: {venda_final}")
        cur.execute("SELECT * FROM venda WHERE data_venda BETWEEN ? AND ?", (venda_inicial, venda_final))
        result = cur.fetchall()
        print(f"result: {result}")
        return render_template('cadastro/contratos_finalizados.html', result=result, resp=resp)
           
               

    elif resp is None:
        if tipo_usuario == 'vendas':
            print(f"Tipo de usuário: {tipo_usuario}")
            query = "SELECT * FROM venda WHERE status <>'contrato finalizado'"
            result = query_db(query)
            return render_template('cadastro/acompanhar_cnt.html', result=result, resp=resp)
        elif tipo_usuario == 'cadastro':
            print(f"Tipo de usuário: {tipo_usuario}")
            query = "SELECT * FROM venda WHERE status = 'Enviado ao cadastro' OR status = 'entrevista online enviada'" 
            result = query_db(query)
            if result is None:
               return render_template('cadastro/sem_registro.html ', result=result, resp=resp)
            return render_template('cadastro/acompanhar_cnt.html', result=result, resp=resp)
        elif tipo_usuario == 'financeiro':
            print(f"Tipo de usuário: {tipo_usuario}")
            query = "SELECT * FROM venda WHERE status ='enviado para financeiro' OR status = 'boleto emitido'"
            result = query_db(query)
            return render_template('cadastro/acompanhar_cnt.html', result=result, resp=resp)
        elif tipo_usuario == 'administrativo':
            print(f"Tipo de usuário: {tipo_usuario}")
            query = "SELECT * FROM venda WHERE status ='entrevista agendada' OR status = 'analise de declaração'OR status= 'geração de kit' OR status = 'Enviado ao cadastro'"
            result = query_db(query)

            return render_template('cadastro/acompanhar_cnt.html', result=result, resp=resp)
        
@cad_bp.route('/detalhes_cnt', methods=['POST', 'GET'])
@acesso('vendas', 'cadastro', 'administrativo','financeiro')
@hierarquia('supervisor', 'agente', 'vendedor')
def detalhes_cnt():
    id = request.args.get('proposta')
    print(f"ID recebido: {id}")

      
    conn = sqlite3.connect(current_app.config['DATABASE'])
    cur = conn.cursor()

    # Buscar os detalhes da venda
    cur.execute("SELECT * FROM venda WHERE numero_proposta = ?", (id,))
    venda = cur.fetchone()

    if venda is None:
        cur.close()
        conn.close()
        return "Registro não encontrado", 404

    # Buscar os responsáveis relacionados à venda
    cur.execute("SELECT * FROM responsavel WHERE proposta_id = ?", (id,))
    responsaveis = cur.fetchall()

    # Buscar os titulares relacionados à venda
    cur.execute("SELECT * FROM titulares WHERE proposta_id = ?", (id,))
    titulares = cur.fetchall()

    # Buscar os dependentes relacionados à venda
    cur.execute("SELECT * FROM dependentes WHERE proposta_id = ?", (id,))
    dependentes = cur.fetchall()

    cur.close()
    conn.close()

    # Renderizar o template com os dados
    return render_template(
        'cadastro/detalhes_cnt.html',
        venda=venda,
        responsaveis=responsaveis,
        titulares=titulares,
        dependentes=dependentes
    )

@cad_bp.route('/alterar_proposta', methods=['POST', 'GET'])
@acesso('vendas', 'cadastro', 'administrativo', 'financeiro')
@hierarquia('supervisor','agente','vendedor')
def alterar_proposta():
    proposta= request.args.get('proposta')
    
    
    return render_template('cadastro/alterar_proposta.html', proposta=proposta)
    
@cad_bp.route('/alterar_registro', methods=['POST', 'GET'])

@acesso('vendas', 'cadastro', 'administrativo', 'financeiro')
@hierarquia('supervisor','agente')
def atualizar_cnt():
    contrato = request.args.get('contrato')  # Para GET
    proposta = request.args.get('proposta')
    id = request.args.get('id')
    tipo_usuario = session.get('tipo_usuario')
    last_resp= request.args.get('last_resp')
    status = request.args.get('status')

    if status == 'contrato finalizado':
        flash('Contrato já finalizado. Não é possível alterar.', 'error')
        return redirect(url_for('cad.detalhes_cnt', id=id, proposta=proposta, contrato=contrato,tipo_usuario=tipo_usuario))

    print(id, proposta,tipo_usuario)
    
    if  not contrato:
        return redirect(url_for('cad.adicionar_cnt', id=id,proposta=proposta,contrato=contrato,tipo_usuario=tipo_usuario,area=last_resp))

    print(f"Contrato: {contrato}, Proposta: {proposta}, ID: {id}")
  
    print(tipo_usuario)
    
    return render_template('cadastro/alterar_cnt.html',id=id,contrato=contrato, proposta=proposta, area=tipo_usuario,last_resp=last_resp)
    


@cad_bp.route('/adicionar_cnt', methods=['GET','POST'])
@acesso('cadastro','administrativo')
@hierarquia('supervisor','agente')
def adicionar_cnt():
    id =request.args.get('id')
    id = int(id)
    proposta = request.args.get('proposta')
    print(id, proposta)


    
    if request.method == 'POST':
        contrato=request.form.get('contrato')

        conn = sqlite3.connect(current_app.config['DATABASE'])
        cur = conn.cursor()
        cur.execute("UPDATE venda SET status = ? WHERE id = ?", (contrato, id))
        cur.execute("UPDATE venda SET status = 'enviado para Declaração de Saúde WHERE id = ?" ,(id))
        conn.commit()
        cur.close()
        conn.close()
        return url_for('cad.alterar_registro')

    return render_template('cadastro/adicionar_cnt.html',id=id, proposta=proposta)


@cad_bp.route('render_doc_get', methods=['POST', 'GET'])
@acesso('vendas', 'cadastro')
@hierarquia('supervisor','agente','vendedor')

def render_page_doc():
    proposta = request.args.get('proposta')
    print(f"Proposta recebida: {proposta}")
    return render_template('cadastro/adicionar_documento.html', proposta=proposta)

@cad_bp.route('adicionar_doc', methods=['POST', 'GET'])
@acesso('vendas', 'cadastro')
@hierarquia('supervisor','agente','vendedor')
def adicionar_doc():
    classe_usuario = session.get('classe_usuario')
    print(f"Tipo de usuário: {classe_usuario}")
    if classe_usuario == 'vendedor':
        resp = session.get('user_nome')
    import os
    from werkzeug.utils import secure_filename
    from flask import request, redirect, url_for, flash, render_template
    ALLOWED_EXTENSIONS = {'rar', 'zip'}
    proposta = request.args.get('proposta')
    print(f"Proposta recebida: {proposta}")

    def allowed_file(filename):
        return '.' in filename and filename.rsplit('.', 1)[1].lower() in ALLOWED_EXTENSIONS

    if request.method == 'POST':
        if 'arquivos' not in request.files:
            flash('Nenhum arquivo selecionado.')
            return redirect(request.url)
        arquivos = request.files.getlist('arquivos')
        # Salva na pasta static/Documentos_contrato de forma dinâmica
        base_folder = os.path.join(os.getcwd(), 'static', 'Documento_propostas' )
        base_folder = os.path.abspath(base_folder)
        if not proposta:
            flash('Proposta não informada.')
            return redirect(request.url)
        proposta_folder = os.path.join(base_folder, str(proposta))
        os.makedirs(proposta_folder, exist_ok=True)
        for arquivo in arquivos:
            if arquivo and allowed_file(arquivo.filename):
                ext = arquivo.filename.rsplit('.', 1)[1].lower()
                filename = f"proposta {proposta}.{ext}"
                arquivo.save(os.path.join(proposta_folder, filename))
                update_db("""
                    UPDATE venda SET documento_enviado = 1 WHERE numero_proposta = ?
                """, (proposta,))
            else:
                flash('Tipo de arquivo não permitido.')
                return redirect(request.url)
        flash('Arquivos enviados com sucesso!')
        return redirect(url_for('auth.redir_atent'))
    return redirect(url_for('auth.redir_atent'))

@cad_bp.route('gravar_alteracao', methods=['POST'])
@acesso('vendas', 'cadastro', 'administrativo', 'financeiro')
@hierarquia('supervisor','agente','vendedor')

def gravar_alteracao():

    id= request.args.get('id')
    print(f"ID recebido: {id}")

app/routes/generic.py
from flask import Blueprint, render_template, session, redirect, url_for

generic_bp = Blueprint('generic', __name__, template_folder='../templates/generic')

@generic_bp.route('/')
def home():
    if 'user_id' not in session:
        return redirect(url_for('auth.login'))
    return render_template('base1.html', usuario=session,usuario_nome=session.get('user_nome'))

@generic_bp.route('/profile')
def profile():
    if 'user_id' not in session:
        return redirect(url_for('auth.login'))
    return render_template('profile.html', usuario_nome=session.get('user_nome'),usuario_tipo=session.get('tipo_usuario'))

@generic_bp.route('/settings')
def settings():
    if 'user_id' not in session:
        return redirect(url_for('auth.login'))
    return render_template('settings.html', usuario=session)

app/routes/home.py
from flask import Blueprint, render_template, request, sessions,session
from ..models.database import query_db
import re
from app.utils import login_required

home_bp = Blueprint('home', __name__)

@home_bp.route('/')
@login_required
def index():
    nome= session.get('id')
    print(nome)
    return render_template('index.html')

app/routes/pdf.py
from flask import Flask, Blueprint, request, render_template, redirect, send_file, url_for
import os
from app.routes.doc_gen import limpar_pasta_saida
from app.utils import acesso
from werkzeug.utils import secure_filename
from PyPDF2 import PdfMerger
#from pdf2image import convert_from_path
import sqlite3
import re
import glob

app = Flask(__name__)

# Caminho base do projeto
BASE_DIR = os.path.abspath(os.path.dirname(__file__))
UPLOAD_FOLDER = os.path.join(BASE_DIR, 'uploads')
FRONT_FOLDER = os.path.join(BASE_DIR, 'static', 'frontal-card')
DATABASE = os.path.join(BASE_DIR, 'MHV_DB.db')


# Configurações do aplicativo
app.config['UPLOAD_FOLDER'] = UPLOAD_FOLDER
app.config['ALLOWED_EXTENSIONS'] = {'pdf'}
app.config['MAX_CONTENT_LENGTH'] = 10 * 1024 * 1024  # Limite de 10MB para upload

# Certifica-se de que os diretórios necessários existem
for folder in [UPLOAD_FOLDER, FRONT_FOLDER]:
    if not os.path.exists(folder):
        os.makedirs(folder)

def allowed_file(filename):
    """Verifica se o arquivo é permitido."""
    return '.' in filename and filename.rsplit('.', 1)[1].lower() in app.config['ALLOWED_EXTENSIONS']

def combine_pdfs(front_pdf, back_pdf, output_pdf):
    """Combina as páginas dos PDFs (frontal e traseira) em um único PDF."""
    try:
        merger = PdfMerger()
        merger.append(front_pdf)  # Adiciona a página da frente
        merger.append(back_pdf)   # Adiciona a página de trás
        merger.write(output_pdf)
        merger.close()
    except Exception as e:
        raise RuntimeError(f"Erro ao combinar PDFs: {e}")

pdf_bp = Blueprint('pdfgen', __name__)

@pdf_bp.route('/criar_card', methods=['GET', 'POST'])
@acesso('cadastro', 'cobranca','administrativo')

def create_card():
        return render_template("cadastro/create_card.html")

@pdf_bp.route('/upload', methods=['POST'])
def upload_files():
    """Rota para fazer upload do arquivo PDF traseiro e combinar com a arte frontal."""
    if 'back_pdf' not in request.files:
        return 'Arquivo traseiro não foi enviado.', 400

    back_file = request.files['back_pdf']

    # Verifica se o diretório frontal existe
    front_files = glob.glob(os.path.join(FRONT_FOLDER, '*.pdf'))
    if not front_files:
        return 'Nenhuma arte frontal encontrada no diretório especificado.', 404

    # Seleciona o primeiro arquivo encontrado
    front_path = front_files[0]

    if back_file and allowed_file(back_file.filename):
        try:
            # Salvar o arquivo traseiro
            back_filename = secure_filename(back_file.filename)
            back_path = os.path.join(app.config['UPLOAD_FOLDER'], back_filename)
            back_file.save(back_path)

            # Gerar o PDF combinado
            output_pdf = os.path.join(app.config['UPLOAD_FOLDER'], 'digital_id-MHVIDA.pdf')
            combine_pdfs(front_path, back_path, output_pdf)

            # Redirecionar para renderizar o PDF
            return redirect(url_for('pdfgen.download_pdf', pdf_path=output_pdf))
        except Exception as e:
            return f"Erro ao processar os arquivos: {e}", 500

    return 'Arquivo inválido. Certifique-se de enviar um arquivo PDF traseiro.', 400

@pdf_bp.route('/download_pdf')
def download_pdf():
    """Permite o download do PDF gerado."""
    pdf_path = os.path.abspath(request.args.get('pdf_path'))
    if not os.path.exists(pdf_path):
        return 'O arquivo PDF especificado não foi encontrado.', 404

    return send_file(pdf_path, as_attachment=True)




if __name__ == '__main__':
    app.register_blueprint(pdf_bp)
    app.run(debug=True)

app/templates/cadastro/adicionar_cnt.html
{% extends "base1.html" %}
{% block title %}Alterar Cadastro{% endblock %}
{% block content %}



<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <div class="container">
        <!-- Botão de fechar -->
       
            <div class="divisoria2">
                 <div class="close-btn-container">
            <a class="close-btn" href="javascript:void(0);" onclick="goBack()" class="close-btn"><<</a>
        </div>
        <h1>Proposta {{proposta}}</h1>
        <h3 hidden>id: {{id}}</h3>

        <div>
            <h2>Adicionar numero de contrato à proposta</h2>
        </div>
    
       
        <form method="POST" action="{{ url_for('cad.gravar_alteracao',id=id) }}">
            <label for="status">atribuir contrato:</label>
            <input type="text" id="status" name="status" placeholder="digite o número do contrato" required>
            <input type="hidden" name="info" value="numero_contrato">    
            <button class="btn" type="submit">alterar</button>
        </div>

            

        </div>
        </form>


    </div>
    
</body>
<script>
    function goBack() {
        if (document.referrer) {
            // Voltar para a página anterior
            window.history.back();
        } else {
            // Redirecionar para a home se não houver página anterior
            window.location.href = '/';
        }
    }
</script>
</html>

{% endblock %}

    

app/templates/cadastro/adicionar_documento.html
{% extends 'base1.html' %}

{% block title %}Anexar documentos{% endblock %}
    
    {% block content %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Anexar documentos da proposta</title>
</head>


<body>
    <div class="container">
        <div class="divisoria2">
            <div class="close-btn-container">
                    <a class="close-btn" href="javascript:void(0);" onclick="goBack()" class="close-btn"><</a>
                </div>
    <h1>Anexar documentos da proposta</h1>
    <form action="{{ url_for('cad.adicionar_doc', proposta=proposta) }}" method="POST" enctype="multipart/form-data">
        <label for="arquivos">Selecione os documentos para upload:</label>
        <input type="file" name="arquivos" id="arquivos" multiple required>
        <button type="submit">Enviar</button>
    </form>
</body>
</html>
</div>
</div>

<script>
    function goBack() {
        if (document.referrer) {
            // Voltar para a página anterior
            window.history.back();
        } else {
            // Redirecionar para a home se não houver página anterior
            window.location.href = '/';
        }
    }
</script>
        {% endblock %}

app/templates/cadastro/alterar_cnt.html
{% extends "base1.html" %}
{% block title %}Alterar Situação de contrato{% endblock %}
{% block content %}



<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <div class="container">
        <!-- Botão de fechar -->
        
            <div class="divisoria2">
                <div class="close-btn-container">
                    <a class="close-btn" href="javascript:void(0);" onclick="goBack()" class="close-btn"><</a>
                </div>
                <h1>Proposta: {{proposta}}</h1>
                <h3>contrato: {{contrato}}</h3>
                <h3 hidden>id: {{id}}</h3>
                <p>Área: {{area}}</p>
                <p hidden>ultimo responsavel:{{last_resp}}</p>
                
                <br>
                <div>
                    <h2>mudar situação do contrato para:</h2>
                </div>
    
            <div class="form-field">
                <form method="POST" action="{{ url_for('cad.gravar_alteracao', id=id) }}">
                    <label for="status"></label>
                    <select id="status" name="status" required>
                        <option value="" disabled selected>selecione</option>
                        
                        {% if area == 'cadastro' %}
                        <option value="entrevista online enviada">entrevista online enviada</option>
                        <option value="enviado para financeiro">Enviar para financeiro</option>
                        <option value="analise de declaração">Enviar para analise</option>
                        
                           
                        {% elif area == 'financeiro' %}
                        <option value="boleto emitido">boleto emitido</option>
                        <option value="geração de kit">enviado para confexão de kit</option>
                        {% elif area == 'administrativo' %}
                        <option value="entrevista agendada">entrevista Agendada</option>
                        <option value="geração de kit">gerar kit</option>
                         {% if last_resp == 'administrativo'  %}
                                <option value="contrato finalizado">contrato finalizado</option>
                            {% endif %}


                        {% else %}
                        <option value="status indefinido">Status indefinido</option>
                        {% endif %}
                    </select>
                    <input type="hidden" name="info" value="status">
                    <br><br>
                    <button class="btn" type="submit">alterar</button>
        
            </div>
             
            
        </div>
        </form>


    </div>
    
</body>
<script>
    function goBack() {
        if (document.referrer) {
            // Voltar para a página anterior
            window.history.back();
        } else {
            // Redirecionar para a home se não houver página anterior
            window.location.href = '/';
        }
    }
</script>
</html>

{% endblock %}

    

app/templates/cadastro/create_card.html
{% extends 'base1.html' %}

{% block title %}Gerador de carteirinhas{% endblock %}

{% block content %}
<div class= container>
<div class="divisoria2">
    <div class="close-btn-container">
        <a class="close-btn" href="{{ url_for('generic.home') }}"class="close-btn"><</a>
    </div>
    <h1>Gerador de carteirinhas</h1>
    <h3>Selecione o arquivo PDF da parte frontal da carteirinha:</h3>

    <form action="{{ url_for('pdfgen.upload_files') }}" method="POST" enctype="multipart/form-data">
                
        <label class="info" for="back_pdf">Selecione o PDF da Parte Traseira:</label>
        <input class="info" type="file" name="back_pdf" required><br><br>

        <button class="btn" type="submit">Gerar PDF</button>
    </form>
</div>
</div>


{% endblock %}

app/templates/cadastro/definir.html
{% extends 'base1.html' %}

{% block title %}Filtragem de Contratos{% endblock %}

{% block content %}


<div class="container">
    <div class="divisoria2">
        <div class="close-btn-container">
            <a href="{{ url_for('generic.home') }}" class="close-btn">✖</a>
        </div>
        <h1>
            Filtragem de Contratos
        </h1>

        <br><br>

        <form method="GET" action="{{ url_for('cad.acompanhar_cnt') }}">
            <label for="data_inicio">Data de Início:</label>
            <input type="date" id="data_inicio" name="venda_inicial">
        
            <label for="data_fim">Data de Fim:</label>
            <input type="date" id="data_fim" name="venda_final">
        
            <button type="submit">Redirecionar</button>
        </form>
    </div>
</div>  
{% endblock %}

app/templates/cadastro/detalhes_cnt.html
{% extends "base1.html" %}
{% block title %}Detalhes de Contrato{% endblock %}
{% block content %}

<link rel="stylesheet" href="{{ url_for('static', filename='css/tabpix.css') }}">

<div class="container-tab-pix">
    <!-- Botão de fechar -->
    <div class="filter-tab-pix2">
        <a class="close-btn" href=" {{ url_for('auth.redir_atent') }} "class="close-btn"><-</a>
        
    </div>
    

    <!-- Título da página -->
    <h1 class="table-title-tab-pix">Detalhes do Contrato</h1>
    
    <!-- Seção de detalhes da venda -->
    <div class="section-tab-pix">
        <h2>Venda</h2>
        <p><strong>Proposta:</strong> {{venda[1]}}</p>
        <p><strong>Contrato:</strong> 
            <a href="{{ url_for('cad.atualizar_cnt', contrato=venda[13], proposta=venda[1], id=venda[0], last_resp=venda[14], status=venda[6]) }}">
                {{ 'N/A' if venda[13] == 'None' else venda[13] }}
            </a>
        </p>
        <p><strong>Valor total:</strong>{{ venda [8] }}</p>
        <p><strong>Data:</strong> {{ venda[2] }}</p>
        <p><strong>Tipo de Contrato:</strong> {{ venda[3] }}</p>
        <p><strong>Produto:</strong> {{ venda[4] }}</p>
        <p><strong>Corretor Responsável:</strong> {{ venda[5] }}</p>
        <p><strong>Status:</strong> 
            <a href="{{ url_for('cad.atualizar_cnt', contrato=venda[13], proposta=venda[1], id=venda[0], last_resp=venda[14], status=venda[6]) }}">
                {{ venda[6] }}
            </a>
        </p>
    </div>
    <br><br>
        <div>
            <a href="{{ url_for('cad.alterar_proposta', proposta= venda[1]) }}" class="btn">Editar Informações</a>
            <a href="{{ url_for('cad.render_page_doc', proposta=venda[1]) }}" class="btn">Anexar Documentos</a>
            <a href="{{ url_for('cad.documento_contrato', proposta=venda[1]) }}" class="btn">Visualizar/Download Documentos</a>
        <div>
    <br><br>
    <!-- Seção de responsáveis -->
    <div class="section-tab-pix">
        <h2>Responsáveis</h2>
        {% if responsaveis %}
        <div class="table-container-tab-pix">
            <table class="table-tab-pix">
                <thead>
                    <tr>
                        <th>Nome</th>
                        <th>CPF</th>
                        <th>Data de Nascimento</th>
                        <th>CEP</th>
                        <th>Celular</th>
                        <th>Email</th>
                        <th>Estado Civil</th>
                    </tr>
                </thead>
                <tbody>
                    {% for responsavel in responsaveis %}
                    <tr>
                        <td>{{ responsavel[2] }}</td>
                        <td>{{ responsavel[3] }}</td>
                        <td>{{ responsavel[4] }}</td>
                        <td>{{ responsavel[5] }}</td>
                        <td>{{ responsavel[6] }}</td>
                        <td>{{ responsavel[7] }}</td>
                        <td>{{ responsavel[8] }}</td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
        {% else %}
        <p class="no-results-tab-pix">Nenhum responsável encontrado.</p>
        {% endif %}
    </div>

    <!-- Seção de titulares -->
    <div class="section-tab-pix">
        <h2>Titulares</h2>
        {% if titulares %}
        <div class="table-container-tab-pix">
            <table class="table-tab-pix">
                <thead>
                    <tr>
                        <th>Nome</th>
                        <th>CPF</th>
                        <th>Data de Nascimento</th>
                        <th>Idade</th>
                        <th>CEP</th>
                        <th>Celular</th>
                        <th>Email</th>
                        <th>Estado Civil</th>
                        <th>Nome da Mãe</th>
                        <th>Sexo</th>
                    </tr>
                </thead>
                <tbody>
                    {% for titular in titulares %}
                    <tr>
                        <td>{{ titular[2] }}</td>
                        <td>{{ titular[3] }}</td>
                        <td>{{ titular[4] }}</td>
                        <td>{{ titular[5] }}</td>
                        <td>{{ titular[6] }}</td>
                        <td>{{ titular[7] }}</td>
                        <td>{{ titular[8] }}</td>
                        <td>{{ titular[9] }}</td>
                        <td>{{ titular[10] }}</td>
                        <td>{{ titular[12] }}</td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
        {% else %}
        <p class="no-results-tab-pix">Nenhum titular encontrado.</p>
        {% endif %}
    </div>

    <!-- Seção de dependentes -->
    <div class="section-tab-pix">
        <h2>Dependentes</h2>
        {% if dependentes %}
        <div class="table-container-tab-pix">
            <table class="table-tab-pix">
                <thead>
                    <tr>
                        <th>Nome</th>
                        <th>CPF</th>
                        <th>Data de Nascimento</th>
                        <th>Grau de Parentesco</th>
                    </tr>
                </thead>
                <tbody>
                    {% for dependente in dependentes %}
                    <tr>
                        <td>{{ dependente[2] }}</td>
                        <td>{{ dependente[3] }}</td>
                        <td>{{ dependente[4] }}</td>
                        <td>{{ dependente[5] }}</td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
        {% else %}
        <p class="no-results-tab-pix">Nenhum dependente encontrado.</p>
        {% endif %}
    </div>
</div>

<script>
    function goBack() {
        if (document.referrer) {
            // Voltar para a página anterior
            window.history.back();
        } else {
            // Redirecionar para a home se não houver página anterior
            window.location.href = '/';
        }
    }
</script>

{% endblock %}

app/templates/cadastro/home.html
{% extends 'base.html' %}

{% block title %}Bem-vindo{% endblock %}

{% block content %}
<div class="container-cards">
    <a class="btn" href="{{ url_for('pdfgen.create_card') }}">criar carteirinha</a> <br>
    <a class="btn" href="">lote de telemedicina</a>
    <a class="btn" href="{{ url_for('doc_gen.gerar_documentos') }}">gerador de kit</a>
    <a class="btn" href="{{ url_for('doc_gen.gerar_documentos') }}">gerador de kit</a>
        <br><br>
    
</div>
<div class="welcome">
    
    


{% endblock %}